[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
piona_minter = "3VMvufM48KC5U57LvLqMUNkRzzvRPYMnipAEHdCZrmxR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/hoooooou_jun/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
